### ISSUE TITLE
global: rename async argument

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-github#31]
Avoid confusion with `async` keyword: https://docs.python.org/3/reference/compound_stmts.html#async-def

**Comment by saksham15082** [comment]
i would like to work on this.

**Comment by saksham15082** [comment]
@jirikuncar  in which files is the change required

**Comment by cglewis** [comment]
@jirikuncar are you referring the `async_hooks` such as this: ?

https://github.com/inveniosoftware/invenio-github/blob/901f396c191a6e50b62eecd6628e7aca1d327174/invenio_github/api.py#L133

Do you just want them renamed to something else, or?

**Comment by jirikuncar** [comment]
@cglewis I was referring to https://github.com/inveniosoftware/invenio-github/blob/901f396c191a6e50b62eecd6628e7aca1d327174/invenio_github/api.py#L157

**Comment by cglewis** [comment]
gotcha, i'll look into this.
