### ISSUE TITLE
Switch doesn't always appear.

### ISSUE THREAD

**Issue by PXke** [inveniosoftware/invenio-github#49]
In some rare case the switch doesn't appear, and we can see just a checkbox.

It is easier to reproduce with Safari. 

![screen shot 2017-05-31 at 17 05 51](https://user-images.githubusercontent.com/790766/28869931-bd09431c-777e-11e7-9b6d-9d7405dff840.png)

**Comment by lnielsen** [comment]
Do you have more information to go on? Some output from the Safari developer console when this happens?

**Comment by lnielsen** [comment]
Ping @PXke :-)
